version: '3.8'

services:
  vault-server:
    image: ${VAULT_PLUGIN_NAME}
    container_name: ${VAULT_PLUGIN_NAME}
    build:
      context: ./plugin
      dockerfile: .docker/Dockerfile
    command: server
    ports:
      - ${VAULT_SERVER_PORT}:${VAULT_SERVER_PORT}
    networks:
      - vnet
    volumes:
      - ./plugin/.docker/config:/vault/config
      - ./plugin/.docker/data:/vault/data
      - ./plugin/.docker/logs:/vault/logs
    environment:
      VAULT_ADDR: 'http://127.0.0.1:${VAULT_SERVER_PORT}'

networks:
  vnet:
    name: vnet
    external: true
